# Generated by Django 2.2.6 on 2019-11-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20191105_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='snippet',
            field=models.TextField(default='snippet here', help_text='Copy a small part of your content text here.'),
            preserve_default=False,
        ),
    ]
